spring:
  application:
    name: JRegistryClient

server:
  port: 6602


netty:
  host: 127.0.0.1
  port: 6604

ssh:
  enabled: true
  host: 127.0.0.1
  port: 2222
  host-key-path: /opt/.jregistryclient_hostkey.ser
  auth:
    username: admin
    password: 123
