spring:
  application:
    name: JRegistryClient

server:
  port: 6604


netty:
  host: 127.0.0.3
  port: 6303

ssh:
  enabled: true
  host: 127.0.0.4
  port: 2222
  host-key-path: /var/tmp/.jregistryclient_hostkey.ser
  auth:
    username: admin
    password: 123
